theme: jekyll-simple-dark
plugins:
- jekyll-remote-theme
logo: /Assets/seal-ough.gif
title: AGenericWiki
tagline: "It's a wiki, what else?"
description: This is mainly used to keep track of stuff and lore but mainly yeah lore, if you want some like more help or need something that is canon added to the wiki that is not here already then DM on comms server.
